### ISSUE TITLE
Bird Target ID 6 Missing?

### ISSUE THREAD

**Issue by ZaydH** [wronnyhuang/metapoison#2]
Thank you for posting this project.  It is very helpful.

In the repo's [main README](https://github.com/wronnyhuang/metapoison/blob/master/README.md), it states regarding the posted datasets that `Target bird IDs 0 and 6 are most likely to work.`

Looking at the [DropBox page](https://www.dropbox.com/sh/4114nvnnx9b4eom/AAAo1NiBKqU8c9ushPotIaCba?dl=0), it looks like target ID 6 is missing in all folders.  Below is a screenshot of the folder with 5,000 poisoned examples:

![image](https://user-images.githubusercontent.com/6292018/103657785-2f3c6600-4f1f-11eb-9469-b9941d56f585.png)

Target ID 6 seems to be missing for all of the different quantities of poisoning (i.e., `npoison_xxx`).

It is very possible I overlooked something.  My apologies if this is an obviously dumb question.

**Comment by wronnyhuang** [comment]
Thanks for bringing this to my notice. I have uploaded targetid_6 to the dropbox. Let me know if it still does not work
