### ISSUE TITLE
Can we poison for a batch of images?

### ISSUE THREAD

**Issue by Josh1108** [wronnyhuang/metapoison#4]
Thanks for providing the code for this paper, it was a great read. 

I was a little confused about one aspect - Can we poison for a batch of images? To expand on this - If I _always_ want a parrot to be misclassified as a dog, is that possible? Or does the current method only work on classifying one particular parrot image as a dog.

For testing purposes, I could only find one target image in the poisoned dataset which makes me believe that MetaPoison would work only on misclassifying one image. Is that so?

**Comment by wronnyhuang** [comment]
It's not implemented in the current repository but that's certainly
possible. Just set the adversarial loss to be not just the loss for that
single bird target, but the average of the losses for multiple bird
targets. It should not be that hard to modify the code to do that.

There are other pairs that we verified the poisoning works on. For example
you can try frog plane which we also reported in the paper. Each pair has
its own efficacy. We did a more comprehensive study on this in the
supplemental material where we tried all 100 possible pairs from the cifar
dataset at a smaller scale
